[package]
name = "mcap-viewer"
version = "0.1.0"
authors = ["Jiangeng Dong <dongjiangeng@gmail.com>"]
edition = "2021"
rust-version = "1.71"

[workspace]
members = [
    "crates/mcap",
    "crates/mcap_decoder",
    "crates/mcap_ros2_decoder",
    "crates/mcap_viewer_storage",
]

[dependencies]
egui = "0.23.0"
eframe = { version = "0.23.0", default-features = false, features = [
    "default_fonts", # Embed the default egui fonts.
    "glow",          # Use the glow rendering backend. Alternative: "wgpu".
    "persistence",   # Enable restoring app state when restarting the app.
] }
egui_plot = "0.23.0"
egui_dock = { version = "0.8.1", features = ["serde"] }

# You only need serde if you want app persistence:
serde = { version = "1", features = ["derive"] }

# third-party dependencies:
log = "0.4"
env_logger = "0.10"

# our dependencies:
mcap = { version = "0.7.2", path = "crates/mcap" }
mcap_ros2_decoder = { version = "0.1", path = "crates/mcap_ros2_decoder" }
mcap_viewer_storage = { version = "0.1.0", path = "crates/mcap_viewer_storage" }
mcap_decoder = { version = "0.1.0", path = "crates/mcap_decoder" }
anyhow = "1.0.75"
egui_autocomplete = { version = "1.0.0", features = ["serde"] }
clap = { version = "4.4.6", features = ["derive"] }
chrono = "0.4.31"
rfd = "0.12.0"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
debug = true

[profile.dev.package."*"]
opt-level = 3

[profile.bench]
debug = true

[patch.crates-io]
egui_autocomplete = { git = "https://github.com/JiangengDong/egui_autocomplete.git", branch = "jiangeng/use-str-iterator" }
